[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dreamo"
version = "0.1"

[tool.setuptools.packages.find]
include = ["dreamo"]

[tool.ruff]
line-length = 120
exclude = ["tools"]
extend-exclude = ["__pycache__", "*.pyc", "*.egg-info", ".cache"]
select = ["E", "F", "W", "C90", "I", "UP", "B", "C4", "RET", "RUF", "SIM"]
ignore = [
    "UP006",
    "UP007",    
    "UP009",
    "UP035",
    "UP038",
    "E402",
    "RET504",
    "C901",
    "RUF013",
    "B006",
]

[tool.black]
line-length = 119
skip-string-normalization = true
exclude = 'tools'

[tool.isort]
profile = "black"
